-- Task 2: Post-Conversion Profitability
-- Goal: Calculate 5-week post-conversions profit per user
-- Flag users as profitable based on cumulative profit≥0
-- Aggregate by conversion week, country, and channel: total 5-week profit, and % profitable users

-- Key Assumptions:
  -- 5 week = 35 days starting from user's actual conversion date
  -- User level acquisition cost is not available so CPA = total_spend/total_conversions
  -- If spend = 0 then CPA is null
  -- Users with no orders are retained with revenue = 0

-- CTE 1: conversions
-- Standardize conversion_date to DATE format
-- Create a cohort week for grouping the data
WITH conversions AS (
  SELECT
    user_id,
    DATE(conversion_date) AS conversion_date,
    DATE_TRUNC(DATE(conversion_date), WEEK(MONDAY)) AS week,
    country,
    channel
  FROM `assessment.conversion_table`
),

-- CTE 2: conversion_actuals
-- Count number of converted users per cohort in order to calculate CPA
conversion_actuals AS (
  SELECT
    week,
    country,
    channel,
    COUNT(DISTINCT user_id) AS actual_conversions
  FROM conversions
  GROUP BY 1,2,3
),

-- CTE 3: spend_actuals
-- Aggregate marketing spend per cohort
-- This indicates the total cost to acquire users in each cohort
spend_actuals AS (
  SELECT
    DATE(week) AS week,
    country,
    channel,
    SUM(spend) AS actual_spend
  FROM `assessment.spend_table`
  GROUP BY 1,2,3
),

-- CTE 4: cohort_cpa
-- Calculate the cohort level CPA ensuring all the cohorts are retained and if spend is missing then CPA is null
cohort_cpa AS (
  SELECT
    c.week,
    c.country,
    c.channel,
    c.actual_conversions,
    s.actual_spend,
    SAFE_DIVIDE(s.actual_spend, c.actual_conversions) AS cpa_per_user
  FROM conversion_actuals AS c
  LEFT JOIN spend_actuals AS s
    ON c.week = s.week
   AND c.country = s.country
   AND c.channel = s.channel
),

-- CTE 5: user_5w_revenue
-- Calculate revenue generated by each user within 5 weeks of conversion
-- Ensure users with no orders are included
user_5w_revenue AS (
  SELECT
    c.user_id,
    c.conversion_date,
    c.week,
    c.country,
    c.channel,
    COALESCE(SUM(o.revenue), 0) AS revenue_5w
  FROM conversions AS c
  LEFT JOIN `assessment.orders_table` AS o
    ON c.user_id = o.user_id
   AND DATE(o.order_date) >= c.conversion_date
   AND DATE(o.order_date) < DATE_ADD(c.conversion_date, INTERVAL 35 DAY)
  GROUP BY 1,2,3,4,5
),

-- CTE 6: user_profitability
-- Calculate profit per user and assign flag of profitable and non-profitable
-- 1 = Profitable, 0 = Not Profitable
user_profitability AS (
  SELECT
    r.user_id,
    r.conversion_date,
    r.week,
    r.country,
    r.channel,
    r.revenue_5w,
    cpa.actual_spend,
    cpa.actual_conversions,
    cpa.cpa_per_user,
    -- Profit Calculation
    CASE
      WHEN cpa.cpa_per_user IS NULL THEN NULL
      ELSE r.revenue_5w - cpa.cpa_per_user
    END AS profit_5w_per_user,
    -- Profitability Flag
    CASE
      WHEN cpa.cpa_per_user IS NULL THEN NULL
      WHEN r.revenue_5w - cpa.cpa_per_user >= 0 THEN 1
      ELSE 0
    END AS is_profitable
  FROM user_5w_revenue AS r
  LEFT JOIN cohort_cpa AS cpa
    ON r.week = cpa.week
   AND r.country = cpa.country
   AND r.channel = cpa.channel
)

-- Cohort Level profitability summary
SELECT
  week,
  country,
  channel,
  -- Total converted users
  COUNT(DISTINCT user_id) AS converted_users,
  -- Identify missing CPA cases
  COUNTIF(cpa_per_user IS NOT NULL) AS users_with_cpa,
  COUNTIF(cpa_per_user IS NULL) AS users_missing_cpa,
  -- Profitability counts
  COUNTIF(is_profitable = 1) AS profitable_users,
  COUNTIF(is_profitable = 0) AS non_profitable_users,
  -- % of users who are profitable
  SAFE_DIVIDE(
    COUNTIF(is_profitable = 1),
    COUNTIF(cpa_per_user IS NOT NULL)
  ) AS pct_profitable_users,
  -- Aggregate profit metrics
  SUM(profit_5w_per_user) AS total_5week_profit,
  AVG(profit_5w_per_user) AS avg_5week_profit_per_user,
  -- Revenue + cost transparency for validation
  SUM(revenue_5w) AS total_5week_revenue,
  MAX(cpa_per_user) AS cohort_cpa_per_user,
  MAX(actual_spend) AS cohort_spend

FROM user_profitability
GROUP BY 1,2,3
ORDER BY 1,2,3;